
FROM ubuntu:12.10
MAINTAINER Michael Andersen <m.andersen@cs.berkeley.edu>

RUN echo "deb http://ubuntu.cal-sdb.org/ubuntu quantal main universe multiverse" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get dist-upgrade -y
